name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Zig
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y zig
      - name: Install Zig (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install zig
      - name: Install Zig (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install -y zig
      - name: Build
        run: zig build -Doptimize=ReleaseFast
      - name: Package
        shell: bash
        run: |
          mkdir dist
          BIN=zig-out/bin/carna-scis
          if [ "${{ matrix.os }}" = "windows-latest" ]; then BIN="zig-out/bin/carna-scis.exe"; fi
          cp "$BIN" dist/
          cd dist && sha256sum * > SHA256SUMS || shasum -a 256 * > SHA256SUMS
      - uses: actions/upload-artifact@v4
        with:
          name: carna-scis-${{ matrix.os }}
          path: dist/*
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
